<template>
  <div class="recharge">
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
      {{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}{{test}}
  </div>
</template>

<script>
import { mapState } from 'vuex'
import {
  AlertPlugin,
  CellFormPreview,
  Checker,
  Checklist,
  Countdown,
  Countup,
  Divider
} from 'vux'

export default {
  computed: {
    ...mapState(['test'])
  },
  components: {
    AlertPlugin,
    CellFormPreview,
    Checker,
    Checklist,
    Countdown,
    Countup,
    Divider
  }
}
</script>

<style scoped>

</style>

